version: "3.6"
services:
  db:
    container_name: 'db'
    image: mssql:2012
    ports:
       - "8000:8000"
    environment:
       MSSQL_DATABASE: 'Django'
       MSSQL_PASSWORD: '1998@Vamshi'
    #    MSSQL_ROOT_PASSWORD: 'root'
    volumes:
      - 'db:/var/lib/mssql'
    # command: ['mssqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  web:
    build: .
    command: python3 app/manage.py runserver 0.0.0.0:8001 
    volumes:
      - '.:/base_directory'
    ports:
      - "8001:8001"
    depends_on:
      - db
    

volumes:
  redisdata:
  db:
  .: