version: '3'
services:
    python:
      # image: python:3.6
      build:
        context: .
        dockerfile: docker/python/Dockerfile
      volumes:
            - ./Django-crud-application-master:/Django-crud-application-master
      ports:
          - "8000:8000"
      # command: sleep infinity 
      # command: "cd / Django-crud-application-master && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver "
    sql-server:
      # image :  mcr.microsoft.com/mssql/server:2017-latest-ubuntu
      image :  mcr.microsoft.com/mssql/server:2017-latest-ubuntu
      container_name: dbw
      environment:
           - ACCEPT_EULA=Y
           - DB=registrationdb
           - SA_PASSWORD=1998@Vamshi
      ports:
      - "1433:1433"
      volumes:
        # - mssql:/var/lib/mssql/data
        # - sqluser:/var/opt/mssql/sqlserver
        #  - './drive:/var/opt/mssql'
           - '//C/Program Files/Microsoft SQL Server/MSSQL15.MSSQLSERVER/MSSQL/DATA'